//left is fpl, right understat

const playerNameObj = {
    "Aleksandar Mitrović": "Aleksandar Mitrovic",
    "Gabriel Fernando de Jesus": "Gabriel Jesus",
    "Rodrigo Moreno": "Rodrigo",
    "Gabriel Martinelli Silva": "Gabriel Martinelli",
    "Jorge Luiz Frello Filho": "Jorginho",
    "Jefferson Lerma Solís": "Jefferson Lerma",
    "Emiliano Buendía Stati": "Emiliano Buendía",
    "Daniel Castelo Podence": "Daniel Podence",
    "Darwin Núñez Ribeiro": "Darwin Núñez",
    "Joelinton Cássio Apolinário de Lira":  "Joelinton",
    "Thiago Alcántara do Nascimento": "Thiago Alcántara",
    "Ivan Perišić": "Ivan Perisic",
    "Son Heung-min": "Son Heung-Min",
    "Philippe Coutinho Correia": "Philippe Coutinho",
    "David De Gea Quintana": "David de Gea",
    "Oriol Romeu Vidal":"Oriol Romeu",
    "Adama Traoré Diarra": "Adama Traoré",
    "Andreas Hoelgebaum Pereira":"Andreas Pereira",
    "Bruno Borges Fernandes":"Bruno Fernandes",
    "Alisson Ramses Becker":"Alisson",
    "Jonathan Castro Otto":"Jonny",
    'Moisés Caicedo Corozo': 'Moisés Caicedo',
    'Diego Carlos Santos Silva': 'Diego Carlos',
    'Mads Roerslev Rasmussen': 'Mads Roerslev',
    'Marc Cucurella Saseta': 'Marc Cucurella',
    'David Raya Martin': 'David Raya',
    'Marc Roca Junqué': 'Marc Roca',
    'Douglas Luiz Soares de Paulo': 'Douglas Luiz',
    'João Palhinha Gonçalves': 'João Palhinha',
    'Bruno Guimarães Rodriguez Moura': 'Bruno Guimarães',
    'Ederson Santana de Moraes': 'Ederson',
    'Luis Sinisterra Lucumí': 'Luis Sinisterra',
    'Cristiano Ronaldo dos Santos Aveiro': 'Cristiano Ronaldo',
    'Frederico Rodrigues de Paula Santos': 'Fred',
    'Miguel Almirón Rejala': 'Miguel Almirón',
    'Diogo Dalot Teixeira': 'Diogo Dalot',
    'Richarlison de Andrade': 'Richarlison',
    'Pablo Fornals Malla': 'Pablo Fornals',
    "Rodrigo Hernandez": "Rodri",
    "Martin Ødegaard": "Martin Odegaard",
    "Thiago Emiliano da Silva": "Thiago Silva",
    "Lucas Rodrigues Moura da Silva": "Lucas Moura",
    "Fabio Henrique Tavares":"Fabinho",
    "Saïd Benrahma":"Said Benrahma",
    "Bernardo Veiga de Carvalho e Silva":"Bernardo Silva",
    "Emiliano Martínez Romero":"Emiliano Martinez",
    "Clément Lenglet": "Clement Lenglet",
    "Gabriel dos Santos Magalhães":"Gabriel",
    "Carlos Ribeiro Dias":"Cafú",
    "Gonçalo Manuel Ganchinho Guedes": "Gonçalo Guedes", 
    "Moussa Niakhaté":"Moussa Niakhate",
    "Nélson Cabral Semedo":"Nélson Semedo",
    "Pedro Lomba Neto":"Pedro Neto",
    "Rayan Aït-Nouri":"Rayan Ait Nouri",
    "Bobby De Cordova-Reid":"Bobby Reid", 
    "Rúben da Silva Neves":"Rúben Neves",
    "Rúben Nascimento Vinagre":"Rúben Vinagre",
    "Emile Smith Rowe": "Emile Smith-Rowe",
    "Emerson Leite de Souza Junior":"Emerson",
    "Benjamin White":"Ben White",
    "Marc Guéhi":"Marc Guehi",
    "Cheick Doucouré":"Cheick Oumar Doucoure",
    "Hwang Hee-chan":"Hee-Chan Hwang",
    "Matty Cash":"Matthew Cash",
    "Rúben Gato Alves Dias":"Rúben Dias",
    "Fábio Freitas Gouveia Carvalho": "Fabio Carvalho",
    "Halil Dervişoğlu":"Halil Dervisoglu",
    "Armel Bella-Kotchap":"Armel Bella Kotchap",
    "José Malheiro de Sá": "José Sá",
    "Roméo Lavia":"Romeo Lavia"
}

module.exports = { playerNameObj };